#include "../src/main.c"
#include <stdio.h>
#include <stdlib.h>
#include "../src/misc.h"
#include "../src/pgm.h"
#include "../src/svg.h"
#include "../src/polygon.h"
#include "../src/ring.h"
#include "../src/elsdc.h"
#include "../src/main.c"